# Both background cleaning steps off, leaving only the minimal validity cuts.
id: dp1_no_clean
extends: dp1_default.yaml
cleaning:
  background:
    column_redshift_trend:
      enabled: false
    column_isolation_forest:
      enabled: false
