id: clauds_sextractor_nir_default_rand100
sample: configs/samples/clauds_sextractor_nir_default.yaml
stack:
  colors:
    - u-g
    - u-r
    - u-i
    - u-z
    - u-y
    - g-r
    - g-i
    - g-z
    - g-y
    - r-i
    - r-z
    - r-y
    - i-z
    - i-y
    - z-y
    - u-Yv
    - u-J
    - u-H
    - u-Ks
    - g-Yv
    - g-J
    - g-H
    - g-Ks
    - r-Yv
    - r-J
    - r-H
    - r-Ks
    - i-Yv
    - i-J
    - i-H
    - i-Ks
    - z-Yv
    - z-J
    - z-H
    - z-Ks
    - y-Yv
    - y-J
    - y-H
    - y-Ks
    - Yv-J
    - Yv-H
    - Yv-Ks
    - J-H
    - J-Ks
    - H-Ks
  modes: [fcolors]
  r_bin_edges:
    geomspace: { start: 5.0, stop: 1000.0, num: 6 }
  reference_annulus: [2000.0, 4000.0]
  snr_max: 100
  random_correction: true
  random_multiplier: 100
  random_seed: 42
  jackknife: true
  dust_extinction_fit:
    fixed_rv: 3.1
